name: Deploy the build to s3

on:
  push:
    branches: [ master ]


jobs:
  sync_s3_dist_files:
    runs-on: ubuntu-latest
    steps:  
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1 
      
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1'
        SOURCE_DIR: 'dist'