name: Ng Continuous Integration

on:
  pull_request:
    branches: [ master ]
    # auto_merge_enabled: true


jobs:
  # enable-auto-merge
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build -- --prod
      
      - name: Check Whether the build passed or failed
        uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: Failed Task
          path: reports/jest-*.xml    # Path to test results
          reporter: sandeep 